CREATE DATABASE BOOK;
USE BOOK;

CREATE TABLE BOOK_INFO(
BOOKID INT PRIMARY KEY,
BOOKNAME VARCHAR(100),
COST INT,
PUBLISHER VARCHAR(100),
AUTHOR VARCHAR(500),
YEAR INT);

INSERT INTO BOOK_INFO VALUES(11,'RAMAYANA',250,'VVV','VALAMIKI',2000),
(12,'WINGSOFFIRE',500,'VRTY','ABDUL KALAM',1999),
(13,'IGNITED MINDS',200,'RRYT','ABDUKALAM',2001),
(14,'INSPIRING THOUGHT',250,'GYTHVC','ABDULKALAM',2007),
(15,'INDOMITABLE SPIRIT',200,'RYHTU','ABDULKALAM',2006),
(16,'XWORKZ',200,'XWORKZ','AAADA',2016);
INSERT INTO BOOK_INFO VALUES(17,'DRYRH',200,'FTTYA','FFDA',2010);

SELECT * FROM BOOK_INFO;

SELECT BOOKID ,BOOKNAME ,COST FROM BOOK_INFO;

SELECT * FROM BOOK_INFO WHERE PUBLISHER='XWORKZ';

SELECT * FROM BOOK_INFO WHERE AUTHOR LIKE 'SHI%';

SELECT * FROM BOOK_INFO WHERE AUTHOR LIKE 'A%';

SELECT * FROM BOOK_INFO WHERE AUTHOR LIKE '__DA';

SELECT * FROM BOOK_INFO  WHERE YEAR BETWEEN 2000 AND 2011; 

SELECT * FROM BOOK_INFO ORDER BY YEAR DESC;

SELECT * FROM BOOK_INFO ORDER BY AUTHOR='AB%' ASC;

SELECT * FROM BOOK_INFO WHERE PUBLISHER='XWORKZ';

SELECT * FROM BOOK_INFO WHERE AUTHOR LIKE'_R';

SELECT * FROM BOOK_INFO WHERE PUBLISHER LIKE '_R%';

SELECT * FROM BOOK_INFO LIMIT 6 OFFSET 4;

