CREATE DATABASE COLLEGES;
USE COLLEGES;

CREATE TABLE DEPARTMENT_INFO(DEPARTMENT_NAME VARCHAR(100) NOT NULL,
DEPARTMENT_MAIL VARCHAR(200) UNIQUE,
DEPARTMENT_ID INT PRIMARY KEY);

INSERT INTO DEPARTMENT_INFO VALUES('CHEMISTRY','CHS@GMAIL.COM',123);
INSERT INTO DEPARTMENT_INFO VALUES('PHYSICS','PH@GMAIL.COM',345);
INSERT INTO DEPARTMENT_INFO VALUES('MATMETICS','MHS@GMAIL.COM',456);
INSERT INTO DEPARTMENT_INFO VALUES('COMPUTERSCIENCE','CS@GMAIL.COM',789);
INSERT INTO DEPARTMENT_INFO VALUES('ECONOMICS','EC@GMAIL.COM',890);
INSERT INTO DEPARTMENT_INFO VALUES('BOTONY','BT@GMAIL.COM',709);
INSERT INTO DEPARTMENT_INFO VALUES('ZOOLOGY','ZOY@GMAIL.COM',607);
INSERT INTO DEPARTMENT_INFO VALUES('HISTORY','HIS@GMAIL.COM',350);
INSERT INTO DEPARTMENT_INFO VALUES('KANNADA','KAN3@GMAIL.COM',1001);
INSERT INTO DEPARTMENT_INFO VALUES('ENGLISH','ENG@GMAIL.COM',9067);

SELECT * FROM DEPARTMENT_INFO WHERE DEPARTMENT_NAME='MATMETICS';

SELECT * FROM DEPARTMENT_INFO;

SELECT DEPARTMENT_MAIL FROM DEPARTMENT_INFO;

CREATE TABLE TRAINEER(TRAINEER_NAME VARCHAR(100) NOT NULL,
TRAINEER_MAIL VARCHAR(200) UNIQUE,
CONTACT_NUMBER LONG PRIMARY KEY);

DROP TABLE TRAINEER;

CREATE TABLE TRAINEER(TRAINEER_NAME VARCHAR(100) NOT NULL,
TRAINEER_MAIL VARCHAR(200) UNIQUE,
CONTACT_NUMBER INT PRIMARY KEY);

INSERT INTO TRAINEER VALUES('VINODHA','VID2@GMAIL.COM',675843565);
INSERT INTO TRAINEER VALUES('VANNI','VANNI@GMAIL.COM',675843890);
INSERT INTO TRAINEER VALUES('PRGATHI','PRG@GMAIL.COM',998884356);
INSERT INTO TRAINEER VALUES('NIDHI','NIDHI@GMAIL.COM',675843509);
INSERT INTO TRAINEER VALUES('RAMYA','RAM2@GMAIL.COM',67584098);
INSERT INTO TRAINEER VALUES('VANITHA','VAN2@GMAIL.COM',98844355);
INSERT INTO TRAINEER VALUES('DIVYA','DIV2@GMAIL.COM',67583565);
INSERT INTO TRAINEER VALUES('AKSHTA','AKS2@GMAIL.COM',675843009);
INSERT INTO TRAINEER VALUES('UMMA','UA2@GMAIL.COM',67503565);
INSERT INTO TRAINEER VALUES('SEEMA','SEEMA@GMAIL.COM',675843765);

SELECT * FROM TRAINEER;

CREATE TABLE ADMISSIONSECTION(ADMISSION_HEAD VARCHAR(100) NOT NULL,
CONTACT_NUMBER INT PRIMARY KEY,
STUDENT_MAIL VARCHAR(100) UNIQUE);

INSERT INTO ADMISSIONSECTION VALUES('VANNI',67895443,'GYT@GMIAL.COM');
INSERT INTO ADMISSIONSECTION VALUES('NIDHI',678954009,'HIR@GMIAL.COM');
INSERT INTO ADMISSIONSECTION VALUES('AMRUTHA',89076543,'IUY@GMIAL.COM');
INSERT INTO ADMISSIONSECTION VALUES('MAHESH',678954437,'GYUT@GMIAL.COM');
INSERT INTO ADMISSIONSECTION VALUES('TILAK',67895409,'PIN@GMIAL.COM');
INSERT INTO ADMISSIONSECTION VALUES('NITIKA',678954098,'TIY@GMIAL.COM');
INSERT INTO ADMISSIONSECTION VALUES('NITIN',679500097,'YT@GMIAL.COM');
INSERT INTO ADMISSIONSECTION VALUES('NAYANA',67857773,'YUY@GMIAL.COM');
INSERT INTO ADMISSIONSECTION VALUES('NAKSHTRA',67851123,'IUT@GMIAL.COM');
INSERT INTO ADMISSIONSECTION VALUES('GAGAN',67950097,'RET@GMIAL.COM');

SELECT * FROM ADMISSIONSECTION;

CREATE TABLE PLACEMENTCELL(COMPANY_NAME VARCHAR(100) NOT NULL,
COMPANY_ADDRESS VARCHAR(500) UNIQUE,
COMPANY_ID INT PRIMARY KEY,
SALARY_PACKAGE VARCHAR(50) NOT NULL);

DROP TABLE PLACEMENTCELL;

CREATE TABLE PLACEMENTCELL(COMPANY_NAME VARCHAR(100) NOT NULL,
COMPANY_ADDRESS VARCHAR(500) UNIQUE,
COMPANY_ID INT PRIMARY KEY,
SALARY_PACKAGE VARCHAR(50) NOT NULL);


INSERT INTO PLACEMENTCELL VALUES('WIPRO','WHITEFIELD',564,'3LPA');
INSERT INTO PLACEMENTCELL VALUES('INFOSYS','XXX',678,'3LPA');
INSERT INTO PLACEMENTCELL VALUES('TRINITY','YYY',74,'3.5LPA');
INSERT INTO PLACEMENTCELL VALUES('HITECH','MMM',64,'3LPA');
INSERT INTO PLACEMENTCELL VALUES('TCS','AAA',514,'4LPA');
INSERT INTO PLACEMENTCELL VALUES('SNYPE','UUU',98,'5LPA');
INSERT INTO PLACEMENTCELL VALUES('ULTRATECH','BELEGAVI',890,'3LPA');
INSERT INTO PLACEMENTCELL VALUES('HP','CCC',434,'3LPA');
INSERT INTO PLACEMENTCELL VALUES('LENOVO','BBB',894,'2.5LPA');
INSERT INTO PLACEMENTCELL VALUES('APPLE','EEE',945,'3LPA');

SELECT * FROM PLACEMENTCELL WHERE SALARY_PACKAGE='3LPA';

SELECT * FROM PLACEMENTCELL;

CREATE TABLE EXAMCELL(REGISTER_ID INT UNIQUE,
UNIVERSITY_NAME VARCHAR(200) NOT NULL,
EXAM_DATE VARCHAR(50) PRIMARY KEY);

INSERT INTO EXAMCELL VALUES(9129,'MANGLOREUNIVERSITY','6AUG');
INSERT INTO EXAMCELL VALUES(9130,'MANGLOREUNIVERSITY','14AUG');
INSERT INTO EXAMCELL VALUES(9131,'MANGLOREUNIVERSITY','8AUG');
INSERT INTO EXAMCELL VALUES(9132,'MANGLOREUNIVERSITY','9AUG');
INSERT INTO EXAMCELL VALUES(8103,'KUVEMPUUNIVERSITY','6SEP');
INSERT INTO EXAMCELL VALUES(8104,'KUVEMPUUNIVERSITY','12SEP');
INSERT INTO EXAMCELL VALUES(2345,'DARWADUNIVERSITY','19SEP');
INSERT INTO EXAMCELL VALUES(1193,'VTU','6NOV');
INSERT INTO EXAMCELL VALUES(778,'AUTONOMUS','1AUG');
INSERT INTO EXAMCELL VALUES(567,'BENGALURUUNIVERSITY','8FEB');

SELECT * FROM EXAMCELL;

SELECT REGISTER_ID,UNIVERSITY_NAME FROM EXAMCELL;

SELECT COUNT(*) FROM EXAMCELL;





